//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadFuncionarioApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public int RA { get; set; }
        public string NOME { get; set; }
        public Nullable<System.DateTime> DATANASCIMENTO { get; set; }
        public string SEXO { get; set; }
        public string TELEFONE { get; set; }
        public Nullable<int> FILHOS { get; set; }
        public Nullable<decimal> SALARIO { get; set; }
        public string CARGO { get; set; }
        public string CEP { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public Nullable<int> NUMERO { get; set; }
    }
}
